post http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpoZWlub24xNyIsImlkIjoiNjA5MDExMGJiZTU0MWEyMjYwMWVjMzRlIiwiaWF0IjoxNjIwMDY2NTE3fQ.Jjt3tKAsbmETm5foLTjRJBRo50FRJdPd9rdDbrtOoQs

{
    "title": "Default title",
    "url": "https://www.iltalehti.fi/",
    "likes": 5,
    "author": "author",
    "user": "Author"
}