delete http://localhost:3003/api/blogs/60835800da2595bf9194ffcc
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkdpcmRldXgiLCJpZCI6IjYwOGQ2ZWY4OTNjYWFlNDQ2NDgzNzM1NCIsImlhdCI6MTYxOTk2NTI2Mn0.E1qma2Nwr-DmMrcbEjdxFHkhaWL9t0784bafB5Ec4C4