delete http://localhost:3003/api/blogs/60835800da2595bf9194ffcc
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.VA2QKT6Eaz6o3HxnJyfDIJQ_GhFtCAvSr75ojVS1eSs