post http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.VA2QKT6Eaz6o3HxnJyfDIJQ_GhFtCAvSr75ojVS1eSs

{
    "title": "Default title",
    "url": "https://www.iltalehti.fi/",
    "likes": 5,
    "user": ""
}